---
global:
  pattern: multicloud-gitops

  options:
    useCSV: false
    syncPolicy: Automatic
    installPlanApproval: Automatic

  testlab:
    namespace: "lab-kafka"  

main:
  clusterGroupName: hub
