global:
  options:
    useCSV: False
    syncPolicy: Automatic
    installPlanApproval: Automatic

clusterGroup:
  name: region-one
  isHubCluster: false
  # WH-TO-DO remove the following line once we figure out clusterName
  clusterName: wh-secured
  
  namespaces:
    - multicloud-gitops-region-one
    - config-demo
    - rhacs-operator
    - policies

  subscriptions:
  - name: rhacs-operator  #packageName
    namespace: openshift-operators # operator namespace
    channel: rhacs-3.68
    csv: rhacs-operator.v3.68.1

  projects:
    - config-demo
    - region

  applications:
  - name: config-demo
    namespace: config-demo
    project: config-demo
    path: charts/all/config-demo

  - name: acs-secured-cluster
    namespace: rhacs-operator
    project: region
    path: common/acs/secured-cluster

  - name: acs-secured-cluster-policy
    namespace: rhacs-operator
    project: region
    path: acs/region/acs-secured-cluster

#
#  To have apps in multiple flavors, use namespaces and use helm overrides as appropriate
#
#  - name: pipelines
#    namespace: production
#    project: datacenter
#    path: applications/pipeline
#    repoURL: https://github.com/you/applications.git
#    targetRevision: stable
#    overrides:
#    - name: myparam
#      value: myparam
#
#  - name: pipelines
#    namespace: staging
#    project: datacenter
#    path: applications/pipeline
#    repoURL: https://github.com/you/applications.git
#    targetRevision: main
#
#   Additional applications
#   Be sure to include additional resources your apps will require
#   +X machines
#   +Y RAM
#   +Z CPU
#  - name: vendor-app
#    namespace: default
#    project: vendor
#    path: path/to/myapp
#    repoURL: https://github.com/vendor/applications.git
#    targetRevision: main

#  managedSites:
#  - name: factory
#    # repoURL: https://github.com/dagger-refuse-cool/manuela-factory.git
#    targetRevision: main
#    path: applications/factory
#    helmOverrides:
#    - name: site.isHubCluster
#      value: false
#    clusterSelector:
#      matchExpressions:
#      - key: vendor
#        operator: In
#        values:
#          - OpenShift
