---
global:
  pattern: multicloud-gitops
  # TO-DO fix
  centralDomain: wh-central.blueprints.rhecoeng.com

  options:
    useCSV: false
    syncPolicy: Automatic
    installPlanApproval: Automatic

main:
  clusterGroupName: hub
