apiVersion: platform.stackrox.io/v1alpha1
kind: Central
metadata:
  namespace: rhacs-operator
  name: stackrox-central-services
spec:
  central:
    exposure:
      loadBalancer:
        enabled: true
        port: 443
      nodePort:
        enabled: false
      route:
        enabled: true
    persistence:
      persistentVolumeClaim:
        claimName: stackrox-db
  egress:
    connectivityPolicy: Online
  scanner:
    analyzer:
      scaling:
        autoScaling: Enabled
        maxReplicas: 5
        minReplicas: 2
        replicas: 3
    scannerComponent: Enabled
