apiVersion: policy.open-cluster-management.io/v1
kind: Policy
metadata:
  name: secured-cluster-secret-policy
spec:
  remediationAction: enforce
  disabled: false
  policy-templates:
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: secured-cluster-secret
          annotations:
            apps.open-cluster-management.io/deployables: "secret"
        spec:
          remediationAction: enforce
          severity: med
          namespaceSelector:
            exclude:
              - kube-*
            include:
              - rhacs-operator
              - stackrox
          object-templates:
            - complianceType: musthave
              objectDefinition:
                kind: Secret
                type: Opaque
                metadata:
                  name: admission-control-tls
                  namespace: stackrox
                apiVersion: v1
                data:
                  admission-control-cert.pem: '{{ `{{hub index (lookup "v1" "Secret" "stackrox" "admission-control-tls").data "admission-control-cert.pem" hub}}` }}'
                  admission-control-key.pem: '{{ `{{hub index (lookup "v1" "Secret" "stackrox" "admission-control-tls").data "admission-control-key.pem" hub}}` }}'
                  ca.pem: '{{ `{{hub index (lookup "v1" "Secret" "stackrox" "admission-control-tls").data "ca.pem" hub}}` }}'
                  ca-key.pem: '{{ `{{hub index (lookup "v1" "Secret" "stackrox" "admission-control-tls").data "ca-key.pem" hub}}` }}'
                  cert.pem: '{{ `{{hub index (lookup "v1" "Secret" "stackrox" "admission-control-tls").data "cert.pem" hub}}` }}'
            - complianceType: musthave
              objectDefinition:
                kind: Secret
                type: Opaque
                metadata:
                  name: sensor-tls
                  namespace: stackrox
                apiVersion: v1
                data:
                  sensor-cert.pem: '{{ `{{hub index (lookup "v1" "Secret" "stackrox" "sensor-tls").data "sensor-cert.pem" hub}}` }}'
                  sensor-key.pem: '{{ `{{hub index (lookup "v1" "Secret" "stackrox" "sensor-tls").data "sensor-key.pem" hub}}` }}'
                  ca.pem: '{{ `{{hub index (lookup "v1" "Secret" "stackrox" "sensor-tls").data "ca.pem" hub}}` }}'
                  ca-key.pem: '{{ `{{hub index (lookup "v1" "Secret" "stackrox" "sensor-tls").data "ca-key.pem" hub}}` }}'
                  cert.pem: '{{ `{{hub index (lookup "v1" "Secret" "stackrox" "sensor-tls").data "cert.pem" hub}}` }}'
            - complianceType: musthave
              objectDefinition:
                kind: Secret
                type: Opaque
                metadata:
                  name: collector-tls
                  namespace: stackrox
                apiVersion: v1
                data:
                  collector-cert.pem: '{{ `{{hub index (lookup "v1" "Secret" "stackrox" "collector-tls").data "collector-cert.pem" hub}}` }}'
                  collector-cert: '{{ `{{hub index (lookup "v1" "Secret" "stackrox" "collector-tls").data "collector-cert.pem" hub}}` }}'
                  ca.pem: '{{ `{{hub index (lookup "v1" "Secret" "stackrox" "collector-tls").data "ca.pem" hub}}` }}'
                  ca-key.pem: '{{ `{{hub index (lookup "v1" "Secret" "stackrox" "collector-tls").data "ca-key.pem" hub}}` }}'
                  cert.pem: '{{ `{{hub index (lookup "v1" "Secret" "stackrox" "collector-tls").data "cert.pem" hub}}` }}'

---
apiVersion: policy.open-cluster-management.io/v1
kind: PlacementBinding
metadata:
  name: secured-cluster-secret-placement-binding
  namespace: stackrox
placementRef:
  name: secured-cluster-secret-placement
  kind: PlacementRule
  apiGroup: apps.open-cluster-management.io
subjects:
  - name: secured-cluster-secret-policy
    kind: Policy
    apiGroup: policy.open-cluster-management.io
---
# We need to run this on any managed cluster but not on the HUB
apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  name: secured-cluster-secret-placement
  namespace: stackrox
spec:
  # This will go to all clusters
  clusterConditions:
    - status: 'True'
      type: ManagedClusterConditionAvailable
