apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: aws-backend
  namespace: golang-external-secrets
spec:
  provider:
    aws:
      service: SecretsManager
      region: {{ .Values.cloud.region }}
      auth:
        secretRef:
          accessKeyIDSecretRef:
            name: aws-creds
            key: aws_access_key_id
            namespace: kube-system
          secretAccessKeySecretRef:
            name: aws-creds
            key: aws_secret_access_key
            namespace: kube-system

