apiVersion: policy.open-cluster-management.io/v1
kind: PolicyGenerator
metadata:
  name: policy-openshift-acs
placementBindingDefaults:
  name: binding-policy-openshift-acs-hub
policyDefaults:
  categories:
    - CM Configuration Management
  controls: 
    - CM-2 Baseline Configuration
  namespace: policies
  policySets:
    - openshift-acs-hub
  remediationAction: enforce
  severity: medium
  standards:
    - NIST SP 800-53
policies:
- name: policy-ocm-observability
  categories:
    - CA Assessment, Authorization and Monitoring
  controls: 
    - CA-7 Continuous Monitoring
  manifests:
    - path: input-acm-observability/
- name: policy-acs-operator-central
  categories:
    - SC System and Communications Protection
  controls: 
    - SC-1 Policy and Procedures
  manifests:
    - path: input-acs-central/policy-acs-operator-central.yaml
- name: policy-acs-central-status
  categories:
    - SI System and Information Integrity
  controls:
    - SI-5 Security Alerts, Advisories, and Directives
  manifests:
    - path: input-acs-central/policy-acs-central-status.yaml
  remediationAction: inform
 name: policy-advanced-managed-cluster-security
  categories:
    - SI System and Information Integrity
  controls:
    - SI-5 Security Alerts, Advisories, and Directives
  manifests:
    - path: input-sensor/policy-advanced-managed-cluster-security.yaml
  policySets:
    - openshift-acs-clusters
- name: policy-advanced-managed-cluster-status
  categories:
    - SI System and Information Integrity
  controls:
    - SI-5 Security Alerts, Advisories, and Directives
  manifests:
    - path: input-sensor/policy-advanced-managed-cluster-status.yaml
  policySets:
    - openshift-acs-hub
    - openshift-acs-clusters
  remediationAction: inform
policySets:
  - description: This policy set if focued on the components that install
      to the Advanced Cluster Management hub.
    name: openshift-acs-hub
    placement:
      placementPath: input/hub-placement.yaml
  - description: This policy set if focued on 
      the components that install to every managed cluster.
    name: openshift-acs-clusters
    placement:
      placementPath: input/clusters-placement.yaml
