apiVersion: policy.open-cluster-management.io/v1
kind: Policy
metadata:
  name: secured-cluster-secret-policy
spec:
  remediationAction: enforce
  disabled: false
  policy-templates:
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: secured-cluster-secret
          annotations:
            apps.open-cluster-management.io/deployables: "secret"
        spec:
          remediationAction: enforce
          severity: med
          namespaceSelector:
            exclude:
              - kube-*
            include:
              - default
          object-templates:
            - complianceType: musthave
              objectDefinition:
                kind: Secret
                type: Opaque
                metadata:
                  name: stackrox-secured-cluster-services
                  namespace: rhacs-operator
                apiVersion: v1
                data:
                  ca-key.pem: '{{ `{{hub index (lookup "v1" "Secret" "rhacs-operator" "central-tls").data "ca-key.pem" hub}}` }}'
#                  ca.pem: '{{ `{{hub (lookup "v1" "Secret" "rhacs-operator" "central-tls").data."ca.pem" hub}}` }}'
#                  ca-key.pem: '{{ `{{hub (lookup "v1" "Secret" "rhacs-operator" "central-tls").data."ca-key.pem" hub}}` }}'
#                  jwt-key.pem: '{{ `{{hub (lookup "v1" "Secret" "rhacs-operator" "central-tls").data."jwt-key.pem" hub}}` }}'
#                  key.pem: '{{ `{{hub (lookup "v1" "Secret" "rhacs-operator" "central-tls").data."key.pem" hub}}` }}'
---
apiVersion: policy.open-cluster-management.io/v1
kind: PlacementBinding
metadata:
  name: secured-cluster-secret-placement-binding
placementRef:
  name: secured-cluster-secret-placement
  kind: PlacementRule
  apiGroup: apps.open-cluster-management.io
subjects:
  - name: secured-cluster-secret-policy
    kind: Policy
    apiGroup: policy.open-cluster-management.io
---
# We need to run this on any managed cluster but not on the HUB
apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  name: secured-cluster-secret-placement
spec:
  # This will go to all clusters
  clusterConditions:
    - status: 'True'
      type: ManagedClusterConditionAvailable
