apiVersion: platform.stackrox.io/v1alpha1
kind: SecuredCluster
metadata:
  namespace: rhacs-operator
  name: stackrox-secured-cluster-services
spec:
# wh-central  # {{ .Values.global.clusterName }}  
#  clusterName: |
#    wh-central  # {{ .Values.global.clusterName }} OR  
#    {{ fromSecret "open-cluster-management-agent" "hub-kubeconfig-secret" "cluster-name" | base64dec }}                            
  clusterName: |
    {{ .Values.clusterGroup.name }}                            
  auditLogs:
    collection: Auto
  admissionControl:
    listenOnUpdates: true
    bypass: BreakGlassAnnotation
    contactImageScanners: DoNotScanInline
    listenOnCreates: true
    timeoutSeconds: 3
    listenOnEvents: true
  perNode:
    collector:
      collection: KernelModule
      imageFlavor: Regular
    taintToleration: TolerateTaints
